apiVersion: v2
name: karpenter
description: A Helm chart for Karpenter, an open-source node provisioning project built for Kubernetes.
type: application
version: 0.20.0
appVersion: 0.20.0
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle
home: https://karpenter.sh/
icon: https://repository-images.githubusercontent.com/278480393/dab059c8-caa1-4b55-aaa7-3d30e47a5616
sources:
  - https://github.com/aws/karpenter/
dependencies:
  - name: karpenter-core
    version: "v0.0.17"
    repository: "oci://ghcr.io/spring1843/karpenter-core"
  - name: karpenter-crd
    version: "v0.101.153"
    repository: "oci://gallery.ecr.aws/d1w0j9s0/karpenter-crd"
