name: CI-TEST
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  ci-test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          k8sVersion: ["1.21.x", "1.22.x", "1.23.x", "1.24.x"]
    env:
      K8S_VERSION: ${{ matrix.k8sVersion }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-go-and-dependencies
    - run: make ci-test
    - uses: shogo82148/actions-goveralls@v1
      if: env.K8S_VERSION == '1.24.x'
      with:
        path-to-profile: coverage.out
