name: Snapshots
on:
  push:
    branches: [ main ]
permissions:
  id-token: write
jobs:
  snapshots:
    if: github.repository == 'spring1843/karpenter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-go-and-dependencies
      - uses: ./.github/actions/authenticate-aws
      - run: cat ~/.docker/config.json
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: cat ~/.docker/config.json
      - run: make release
